"""Weighted metrics and shift-oriented evaluation utilities."""

from shiftstat.metrics.reliability import (
    brier_decomposition,
    calibration_curve,
    calibration_slope_intercept,
    calibration_summary,
    confidence_conditioned_error,
    expected_calibration_error,
    maximum_calibration_error,
    negative_log_likelihood,
    predictive_entropy_summary,
    probability_bin_summary,
    uncertainty_bucket_summary,
    weighted_ece,
)
from shiftstat.metrics.selective import (
    abstention_rate,
    candidate_thresholds,
    retained_coverage,
    risk_coverage_table,
    selective_accuracy,
    selective_calibration_summary,
    selective_risk,
    selective_summary,
)
from shiftstat.metrics.weighted import (
    compute_effective_sample_size,
    source_separability_score,
    weighted_accuracy,
    weighted_brier_score,
    weighted_log_loss,
    weighted_mae,
    weighted_mse,
)

__all__ = [
    "brier_decomposition",
    "calibration_curve",
    "calibration_slope_intercept",
    "calibration_summary",
    "confidence_conditioned_error",
    "compute_effective_sample_size",
    "candidate_thresholds",
    "expected_calibration_error",
    "maximum_calibration_error",
    "negative_log_likelihood",
    "predictive_entropy_summary",
    "probability_bin_summary",
    "retained_coverage",
    "risk_coverage_table",
    "selective_accuracy",
    "selective_calibration_summary",
    "selective_risk",
    "selective_summary",
    "source_separability_score",
    "abstention_rate",
    "uncertainty_bucket_summary",
    "weighted_accuracy",
    "weighted_brier_score",
    "weighted_ece",
    "weighted_log_loss",
    "weighted_mae",
    "weighted_mse",
]
